### ISSUE TITLE
Blocks being propagated

### ISSUE THREAD

**Issue by crossoveranx** [orbita-center/parity-poa-playground#13]
i follow the instructions and launch the PoA nodes on a remote host, however when I load up the UI monitor for the network, I don't see any blocks being propagated and no nodes that are participating in the network. I can confirm that the nodes are running, but not sure what the issue is.

**Comment by Pzixel** [comment]
Sorry, I don't think anything wrong with the configuration. Try using other client and/or call network directly via RPC, e.g. connect via geth.
