### ISSUE TITLE
block interval?

### ISSUE THREAD

**Issue by drandreaskrueger** [orbita-center/parity-poa-playground#14]
It looks as if under load the block interval settles somewhere around 3 seconds, right?

See one early example run of my [chainhammer](https://gitlab.com/electronDLT/chainhammer/):
```
./tps.py 
versions: web3 4.3.0, py-solc: 2.1.0, solc 0.4.23+commit.124ca40d.Linux.gpp, testrpc 1.3.4, python 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118]
web3 connection established, blockNumber = 75, node version string =  Parity//v1.11.8-stable-92776e4-20180728/x86_64-linux-gnu/rustc1.27.2
first account of node is 0x000a3702732843418D83A03E65A3d9f7aDd58864, balance is 10000000000 Ether
nodeName: Parity, nodeType: Parity, consensus: ???, chainName: parity-poa-playground

Block  75  - waiting for something to happen
(filedate 1534861584) last contract address: 0x5fE887AD9B4452A4793AbB9363558992228cB094
(filedate 1534862035) new contract address: 0xBD45194215D595444c07A591A9D6E5a1fA53f169

starting timer, at block 77 which has  1  transactions; at timecode 23211.441064545
block 77 | new #TX  23 / 3000 ms =   7.7 TPS_current | total: #TX   24 /  3.0 s =   7.9 TPS_average
block 78 | new #TX 163 / 3000 ms =  54.3 TPS_current | total: #TX  187 /  6.1 s =  30.8 TPS_average
block 79 | new #TX  10 / 3000 ms =   3.3 TPS_current | total: #TX  197 /  9.1 s =  21.6 TPS_average
block 80 | new #TX 675 / 5000 ms = 135.0 TPS_current | total: #TX  872 / 14.0 s =  62.4 TPS_average
block 81 | new #TX 186 / 3000 ms =  62.0 TPS_current | total: #TX 1058 / 17.0 s =  62.1 TPS_average
block 82 | new #TX 195 / 3000 ms =  65.0 TPS_current | total: #TX 1253 / 20.1 s =  62.4 TPS_average
block 83 | new #TX 193 / 3000 ms =  64.3 TPS_current | total: #TX 1446 / 22.8 s =  63.3 TPS_average
block 84 | new #TX 200 / 3000 ms =  66.7 TPS_current | total: #TX 1646 / 25.9 s =  63.6 TPS_average
block 85 | new #TX 199 / 3000 ms =  66.3 TPS_current | total: #TX 1845 / 28.9 s =  63.8 TPS_average
block 86 | new #TX 197 / 3000 ms =  65.7 TPS_current | total: #TX 2042 / 32.0 s =  63.9 TPS_average
block 87 | new #TX 198 / 3000 ms =  66.0 TPS_current | total: #TX 2240 / 35.0 s =  64.0 TPS_average
block 88 | new #TX  91 / 3000 ms =  30.3 TPS_current | total: #TX 2331 / 38.1 s =  61.2 TPS_average
block 89 | new #TX   0 / 11000 ms =   0.0 TPS_current | total: #TX 2331 / 49.2 s =  47.4 TPS_average
```

The [gasLimit is at 6 billion](https://github.com/orbita-center/parity-poa-playground/blob/master/parity/config/chain.json#L40) already - correct?

Then the only way to speed this up would be faster blocks, no?

**How can I accelerate the block time?**

Is this the parameter?

```
  "engine": {
    "authorityRound": {
      "params": {
        "stepDuration": "1",
```

https://github.com/orbita-center/parity-poa-playground/blob/master/parity/config/chain.json#L6

stepDuration 1 == 1 second blocktime?

If yes, then why don't we see ~1 second blocktimes?

If no, then how to change the blocktime to something faster than approx 3 seconds?

Thanks!

**Comment by drandreaskrueger** [comment]
why? what for? --> https://gitlab.com/electronDLT/chainhammer/blob/master/parity.md

**Comment by Pzixel** [comment]
Hey!

Sorry, I didn't get what do you mean. Could you please write some clear explanation what issue or suggestion do you have?

**Comment by drandreaskrueger** [comment]
How can I accelerate the block time?

**Comment by Pzixel** [comment]
buy better hardware

**Comment by drandreaskrueger** [comment]
:-) 

hahaha. 

you made my day, with that answer. 

Thanks.

**Comment by drandreaskrueger** [comment]
However, on the same hardware, geth Clique is running 6 times faster than this, quorum IBFT even 8 times.

**Comment by drandreaskrueger** [comment]
is there a chainspec parameter for aura which represents a target "block interval" ?

**Comment by Pzixel** [comment]
Please, stop spamming.

I'm not kidding, you can ask parity guys. You can do nothing if your hardware is not capable to issue cryptosigned blocks every second.

**Comment by drandreaskrueger** [comment]
Thanks. Have a good life.
