### ISSUE TITLE
(FR) script which only deletes the blockchains from all nodes

### ISSUE THREAD

**Issue by drandreaskrueger** [orbita-center/parity-poa-playground#15]
At the moment, Ctrl-C and a new `docker compose up` results in continuation of the previous chain.

How to delete the blockchains on all nodes?  I want to start with a clean slate.

# feature request

Could you please add a 

    kill-databases.sh

script which deletes the blockchains from all nodes.

Thanks a lot!

**Comment by Pzixel** [comment]
docker-compose down -v

**Comment by drandreaskrueger** [comment]
yep, back to block 0, thanks.

I suggest you mention that on https://github.com/orbita-center/parity-poa-playground/blob/master/README.md

**Comment by drandreaskrueger** [comment]
Then don't mention that in your README.md, and let future users search for it themselves, or open yet another issue.

pffff
